### ISSUE TITLE
NameError: name 'Configuration' is not defined

### ISSUE THREAD

**Issue by CharlesWilhelm** [Uelb/pinch-python#2]
Tried with the code example but no luck. 

pip list | grep Pinch
Pinch (0.1.7)
$ cat test.py  
import Pinch

Configuration.x_api_token = 'MY_API_KEY'
Configuration.x_api_email = 'myemail@example.com'
$ python test.py  
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    Configuration.x_api_token = 'MY_API_KEY'
NameError: name 'Configuration' is not defined
$ python --version
Python 2.7.10

Does it ever work for anyone?

**Comment by Uelb** [comment]
The correct import is `from Pinch import *`
Also, who are you ?
